### PR TITLE
Kpack gs

### PR DESCRIPTION
**Pull request by everythingeverywhere**
- updated to new kpack install 

- added dockerhub examples/config

- added simple deploy to k8s

- added `layouts/shortcodes/expand.html` so users can expand different configs

@tybritten for visibility wasn't able to add him as reviewer

### CODE REVIEW

**Review by bryanfriedman — COMMENTED** [review]
@everythingeverywhere Looks like there is some old stuff getting pulled into this too. Maybe we need a new branch for just the kpack update?

**Comment by everythingeverywhere** [comment]
> @everythingeverywhere Looks like there is some old stuff getting pulled into this too. Maybe we need a new branch for just the kpack update?

@bryanfriedman I think I resolved the conflict that was pulled in, also I had deleted the blog I wrote previously by accident but added it back in just now. I am waiting for the spell checkts etc and will verify the files that are within again

**Comment by everythingeverywhere** [comment]
> > @everythingeverywhere Looks like there is some old stuff getting pulled into this too. Maybe we need a new branch for just the kpack update?
> 
> @bryanfriedman I think I resolved the conflict that was pulled in, also I had deleted the blog I wrote previously by accident but added it back in just now. I am waiting for the spell checks etc and will verify the files that are within agai

**Comment by everythingeverywhere** [comment]
passing all checks finally I had messed up merge on last blog, headers have been fixed and ready to merge to tanzu-dev-portal

**Comment by everythingeverywhere** [comment]
Pretty strange all checks had passed a moment ago.. the broken links reported are` http://localhost:1313/developer/` but the `ugo serve` instance that comes up goes to `http://localhost:1313/` 

PR should be ready to go.

**Review by tybritten — CHANGES_REQUESTED** [review]
you need to revert the changes on the springone2020-workshops.md- those are out of date. otherwise looks fine.

**Comment by everythingeverywhere** [comment]
thanks @tybritten !! reverted the file to commit before I stashed the file ready to goooooo

**Review by tybritten — APPROVED** [review]

**Pull request merged**
