### PR TITLE
New Content: Tanzu Application Platform install guide per OS

### PR DESCRIPTION
**Pull request by anthonyvetter**

### CODE REVIEW

**Comment by anthonyvetter** [comment]
@BrianMMcClain would you mind reviewing this one too? The content should be fine but Ben added some shortcodes and some changes to the config.toml I would like another pair of eyes on. From Ben:
```
Hugo changed their requirements. The change to TOML was necessary to allow make preview on machines where the site hasn't been built before (I think).

It allows Hugo to be able to access some Environment variables that are used in some existing shortcodes.

[security.funcs]
  getenv = ['^HUGO_', '^COMMIT_', '^CONTEXT']

See https://github.com/gohugoio/hugo/releases/tag/v0.91.0
```

**Comment by BrianMMcClain** [comment]
Hey @benwilcock! Looking at this now, one thing I wanted to double check, what version of Hugo are you running currently? We've [pinned our release to 0.82.0](https://github.com/vmware-tanzu/tanzu-dev-portal#software-installation-prerequisites) because of an error on newer versions, but this may be the fix for that. I'd still like to do more testing before we bump the version in prod, but would be awesome if this is the fix we'd need to do that :)

**Comment by benwilcock** [comment]
> What version of Hugo are you running currently?

Hey @BrianMMcClain my version is hugo v0.94.2+extended linux/amd64. Came from Homebrew about a week ago.

**Comment by anthonyvetter** [comment]
@BrianMMcClain, @benwilcock: Shall we pull those changes to `config.toml` from this PR and submit it separately then? Besides that, do the short codes look okay? Just don't want to hold up publishing this for testing of an unrelated issue.

**Comment by benwilcock** [comment]
The shortcodes should work on their own without the config.toml change. I would give it a try without the config change but include the shortcodes and see what happens.

**Comment by BrianMMcClain** [comment]
> Shall we pull those changes to `config.toml` from this PR and submit it separately then?

I wouldn't hate that, I _think_ everything looks fine, but there is some more testing I'd like to do before those changes are in production, plus it does seem like something that should be contained in its own PR for future reference. I'll try to look deeper into it ASAP, but I agree, don't want to hold up merging the content.

> Besides that, do the short codes look okay? 

Shortcodes all look good to me, like Ben said it should be unrelated to the config changes, but worth updating the PR without those changes and seeing how the build/preview go

**Comment by anthonyvetter** [comment]
GH Actions are [broke](https://www.githubstatus.com) again for now, but the [preview site](https://deploy-preview-1726--tanzu-dev-portal.netlify.app/developer/guides/tanzu-application-platform-local-devloper-install/) is up and it looks like all the Short Codes are working properly. Alright, as soon as the Actions tests complete, I'll get this merged. Unless there are any objections.

I pulled out the `config.toml` changes and put them in [PR1731](https://github.com/vmware-tanzu/tanzu-dev-portal/pull/1731).

**Pull request merged**
