### PR TITLE
GemFire blog for security manager authentication and authorization

### PR DESCRIPTION
**Pull request by jomartin-999**

### CODE REVIEW

**Comment by jomartin-999** [comment]
Yes it is ready to be reviewed.  Thanks!

**Comment by anthonyvetter** [comment]
Got it. I will submit for editing. That means I need to pull it out into a Google Doc for now (we are working on that process). I will update when it's ready for you to accept/reject changes. Stand by.

**Comment by anthonyvetter** [comment]
Adding this here too, from a Slack conversation: I checked on the status of this today. It is still in the editing hopper and should be completed soon.

**Comment by anthonyvetter** [comment]
@jomartin-999, received the edits back from the editor. [Here](https://docs.google.com/document/d/1Y6n5u9xmCNgfJIlz3WqtgvIx1WzLTC6GfhIliMJW83w/edit) is the Google Doc. Hopefully formatting is preserved so you can just copy it in.

**Comment by jomartin-999** [comment]
@anthonyvetter > Thank you! Updated blog article based on the feedback and edits.

**Review by anthonyvetter — APPROVED** [review]
Looks good. Merging!

**Pull request merged**
