### PR TITLE
Place to work on adding a feedback link

### LINKED ISSUE #742: Add link to each page for feedback
"Have feedback, click here"

This will link the user to a GH issue template in this repo

### PR DESCRIPTION
**Pull request by mikegehard**
Fixes #742

### CODE REVIEW

**Comment by mikegehard** [comment]
Waiting on some design of where to integrate into the site.

**Comment by BrianMMcClain** [comment]
@mikegehard With #937 merged and #918 in progress, are we ok to close this?

**Comment by mikegehard** [comment]
Thanks for the heads up @BrianMMcClain. Is there a place in staging or prod that I can check it out to confirm how it looks?

**Comment by BrianMMcClain** [comment]
@mikegehard for #937 it should be live on every guide/blog/video/etc, basically everything but workshops, which you can see at the bottom of each page:

Screen Shot 2021-06-21 at 3 12 51 PM

Unfortunately the WIP workshop overlay is about where it was last time we spoke in #918, and if you'd like to leave this open until that's completed that works for me too :)

**Comment by mikegehard** [comment]
Since my last day with the Services Strategy team is 6/30, might be best to close this unless you think the workshop stuff will be done by then?

Curious if there's a way to change the test to "Give us feedback"? That allows someone to both leave a bug report but also leave non-bug feedback on ways to improve the articles.

**Pull request closed without merging**
