### PR TITLE
New guide - Test doubles

### PR DESCRIPTION
**Pull request by abasson-vmware**
This pull request creates a new guide, entitled "What Are Test Doubles". It also creates an author page for Alex Basson.

The content needs to be reviewed for conformance to the style guide, and also by a copy editor. As this is my first submission to the TDC, I'd appreciate any help to make this happen.

The PR addresses https://github.com/vmware-tanzu/tanzu-dev-portal/issues/1473

### CODE REVIEW

**Comment by joemoore** [comment]
The build is currently failing because the system wants to automatically link your information [here](https://tanzu.vmware.com/developer/team/). Can you please add a "Team" entry for yourself? Also... welcome to the team!

**Comment by abasson-vmware** [comment]
@joemoore I believe this PR includes a "Team" entry for myself, unless I overlooked something. It's the second commit in the PR. And thanks for the welcome! :)

**Comment by joemoore** [comment]
@abasson-vmware 🤦‍♂️

**Comment by joemoore** [comment]
If I had actually read the error message I would have realized that it was upset about your author photo being a .png instead of a .jpg, which is a built-in assumption the system has. I converted it.

**Comment by anthonyvetter** [comment]
Thank you @abasson-vmware! Welcome and thank you for contributing! Looks like tests are passing and I went ahead and updated the branch. Is this ready for editing and final review then? Or are you still getting other feedback?

**Comment by joemoore** [comment]
I'd say something to consider is the categorization and "levels". @anthonyvetter maybe you can educate us a bit here. Currently it's classified under `Building Modern Applications - Modern Development Practices` but there is only one other categorized as such. Another option might be `Agile Transformation and Practices - Agile Development`, but "Agile" is such a squishy term for something as tactical as this article. Any advice as to where this should go?

**Comment by anthonyvetter** [comment]
@joemoore, ya I see your point. Really, it could go in either place. I don't have a very strong opinion here, but IMO, I think it is better in `Modern Development Practices`. This piece focuses on a way to implement a specific TDD approach. And while TDD is a core tenant of Agile, I think this piece talks about the implementation of testing for testing's sake. Not necessarily through the lens of an Agile methodology. 

Here are some excerpts from the descriptions of each page. 

For `Modern Development Practices`:
`A long development cycle can be frustrating and a massive contribution to slowing down development. A combination of tools and methods can help shorten that cycle and improve the quality of life for developers.`

For `Agile Development`:
`Agile methodologies provide an alternative to the sequential development and long release cycles traditionally associated with Waterfall.`

In addition, the Agile page talks about remote working and team building. So I would say that perhaps a higher level TDD piece (an overview of different approaches like test doubles, for example) might fit on the Agile page. But a piece like this detailing how to actually implement a development practice probably belongs on the Development Practices page. 

I also think about the pages in terms of audience. Who is going to be reading an Agile page? Maybe not the folks looking to implement a testing methodology? Probably folks looking for information on Scrum, XP, etc. I would say devs looking to do implementations are probably more likely to go to a development practices page. 

That said, open to other suggestions or opinions of course. If there are strong(er) feeling from yourself or @abasson-vmware, let me know.

**Comment by joemoore** [comment]
With those definitions "Modern Development Practices" sounds like a good fit.

**Comment by abasson-vmware** [comment]
+1 to "Modern Development Practices"

**Comment by anthonyvetter** [comment]
Ok, sending this over to our editor. Stand by :)

**Comment by joemoore** [comment]
Ship it! 🚀

**Comment by abasson-vmware** [comment]
@joemoore @anthonyvetter Are there any next steps I need to take to move this forward?

**Comment by anthonyvetter** [comment]
The copy editor is looking at this today I believe. I had to port it out to a Google Doc since this editor doesn't work in GH. I will send that over to you as soon as I have it back.

**Comment by anthonyvetter** [comment]
Here is the Google Doc back from the Editor: https://docs.google.com/document/d/14WJLlqouEwHajRtnN060w61wI2VLte91lcRw7cevpU4/edit

**Comment by abasson-vmware** [comment]
@anthonyvetter Thanks for this. I'm not able to view the doc, but I've requested access. As soon as that goes through, I'll take a look at the changes.

**Comment by anthonyvetter** [comment]
@abasson-vmware, Okay your deploy preview is ready. It looks good to me but want to give you the final thumbs up. Let me know and I will get it merged.
https://deploy-preview-1501--tanzu-dev-portal.netlify.app/developer/guides/test-doubles/

**Comment by abasson-vmware** [comment]
Looks good to me! Let's ship it.

**Review by anthonyvetter — APPROVED** [review]
Looks good.

**Pull request merged**
