### PR TITLE
Try lighthouse netlify plugin

### PR DESCRIPTION
**Pull request by bryanfriedman**

### CODE REVIEW

**Comment by bryanfriedman** [comment]
@zmb3 @BrianMMcClain The lighthouse GH action puked a couple too many times for me so I thought I'd give this method a shot. I like this better...we can decide if we want to publish the report to a subdirectory of the site, or we can just view the results within the Netlify app. Let me know what you think.

**Comment by BrianMMcClain** [comment]
This actually might be a good solution. We were looking at addressing the timeout waiting for the preview deploy, but this is a bit more direct. I'm not super familiar right now with how Netlify plugins can tie into GH checks, is there any way to include it in the list of checks on GH? If so, that would be perfect.

Either way, this is cool with me!

**Review by BrianMMcClain — APPROVED** [review]

**Comment by zmb3** [comment]
Where does the report go as configured right now? Is it visible somewhere?

+1 @BrianMMcClain's comment - I would really like to be able to see the checks in the PR, so that we can eventually prevent a PR from being merged if it has accessibility issues, for example.

**Review by zmb3 — APPROVED** [review]

**Comment by bryanfriedman** [comment]
You can see the report in the Netlify deploy build: https://app.netlify.com/sites/tanzu-dev-portal/deploys/609c633ff22e8900082aef1f.

You can set in netlify.toml to publish the report somewhere, and you can also set it to fail if a threshold isn't met: https://github.com/vmware-tanzu/tanzu-dev-portal/blob/lighthouse-plugin/netlify.toml#L24-L37.

We can play with these settings and try it on this PR to see how it works. We can also potentially open a PR against https://github.com/netlify-labs/netlify-plugin-lighthouse if we want to see different behavior?

**Comment by BrianMMcClain** [comment]
I think without setting that `output_path` value in the config, all that's reported is this JSON, right?

```
7:24:16 PM: {
7:24:16 PM:   results: [
7:24:16 PM:     { title: 'Performance', score: 1, id: 'performance' },
7:24:16 PM:     { title: 'Accessibility', score: 0.93, id: 'accessibility' },
7:24:16 PM:     { title: 'Best Practices', score: 1, id: 'best-practices' },
7:24:16 PM:     { title: 'SEO', score: 0.91, id: 'seo' },
7:24:16 PM:     { title: 'Progressive Web App', score: 0.3, id: 'pwa' }
7:24:16 PM:   ]
7:24:16 PM: }
```

Or I might be missing that full breakdown it generates :)

**Comment by bryanfriedman** [comment]
Yeah I guess you're right. I can't find more than that. Should we just set it to publish somewhere? I don't see any real issue with doing that. It's a single line in the config file if we want to try it.

**Comment by BrianMMcClain** [comment]
Yeah I think that would be good, I don't see any harm in it, no different info in it than if someone would to run it themself.

**Comment by bryanfriedman** [comment]
@BrianMMcClain @zmb3 I set this to publish the report only on deploy previews since that's what we were effectively getting anyway. You can get to it via [https://deploy-preview-###--tanzu-dev-portal.netlify.app/developer/lighthouse/](https://deploy-preview-842--tanzu-dev-portal.netlify.app/developer/lighthouse/).

I think this gets us what we want and simplifies the GH actions. Please review and merge.

**Comment by zmb3** [comment]
LGTM!

**Review by zmb3 — APPROVED** [review]

**Pull request merged**
