### PR TITLE
Fix Outcomes Index Styles

### PR DESCRIPTION
**Pull request by jesse-martinez**
Remove flexnowrap, create new CSS class for half width rectangles

### CODE REVIEW

**Comment by zmb3** [comment]
Curious - why a new class for half width instead of `col-6`?

**Comment by zmb3** [comment]
Also, what's going on with git such that there's 20+ merge commits in here? That seems odd.

**Comment by jesse-martinez** [comment]
> Curious - why a new class for half width instead of `col-6`?

Because if you use col-6, then there will be no gap in between the two halves. You can go the route of adding margin/padding to a col-6 but its been making the spacing across the site really inconsistent. There are a lot of elements across the site that are not flush with the max-width of their parent containers. I've found it most effective to just create a new class that is almost 50% and allow the elements to wrap in a flex container that way instead of using col-6 with margin-rights, etc.

**Comment by jesse-martinez** [comment]
@BrianMMcClain @bryanfriedman ready for review/merge. Rachel and I decided to go with 1/3 columns, and we put the other half of the description in the container below, since there was a lot of copy in the hero, which interfered with the hero banner.

**Review by BrianMMcClain — APPROVED** [review]

**Pull request merged**
