### PR TITLE
GemFire blog for security manager authentication only.

### PR DESCRIPTION
**Pull request by jomartin-999**

### CODE REVIEW

**Comment by jomartin-999** [comment]
Linked Issue: https://github.com/vmware-tanzu/tanzu-dev-portal/issues/1582

**Comment by anthonyvetter** [comment]
Submitted for editing. Stand by.

**Comment by anthonyvetter** [comment]
@jomartin-999, your [piece](https://docs.google.com/document/d/1jf99oNPlBswG0LUXHRcGmUNc49x45ETrqb0DIZ5Gwcc/edit) is back from editing. Go ahead and port in the changes and let me know when the PR is ready, and I will get it merged.

**Comment by jomartin-999** [comment]
@anthonyvetter PR is ready after edits.  Thank you!

**Review by anthonyvetter — APPROVED** [review]
Looks good. Merging.

**Pull request merged**
