### PR TITLE
init of spring distributed lock guide and sample

### PR DESCRIPTION
**Pull request by estand64**

### CODE REVIEW

**Comment by anthonyvetter** [comment]
First, again, thank you for the submission. The Developer Center could not exist as it does today without contributions like this, so it is very much appreciated. And this topic is also a great fit for us. 

As far as helping with layout and things, here are a couple points of high-level feedback:
* Not sure if the file `content/guides/spring-integration/index.md` was submitted by mistake? It's... a little short to be a guide :) 
* Consider a prerequisites section. This could be tools they need to have installed, or experience the reader should have to follow along adequately. 
* If appropriate, consider adding images, screenshots, or diagrams to break up this post a bit. 
* Headings should be shorter, and probably not full sentences. So for example, `Needed for the Redis based lock (I'm using Lettuce here, however Spring will also support Jedis if you want to use that):` should be something like `Redis-based locks` (or something better that you decide). 
* Heading shouldn't skip levels (from ## to ####, for example. 
* Each heading should have some body content below that, and in between code samples. Something that provides context for what is in that section.
* You can leave out html formatting if possible, and line breaks. 
* Typical layout for a guide would be something like a heading which describes the larger goal for that section (i.e. Import packages), then a series of explicit steps (numbered 1, 2, 3...) that the reader needs to do to meet the goal of the guide. 
* Consider adding a "call to action" at the end. What do you want the reader to do after going through this guide? Read another guide? Try extending the example? Some solid ideas at the end will help keep the reader learning
* We don't have a hard and fast layout for guides yet, but in the Spring ecosystem, [this](https://tanzu.vmware.com/developer/guides/scs-gs/) one is a good example you might want to look at as an example. And outside of Spring, and possibly a little biased, [this](https://tanzu.vmware.com/developer/guides/argocd-gs/) is another good example of a guide. 

We will probably take another pass at this as far as a review, but this is some initial feedback. Hope it helps and let us know if you have any questions!

**Comment by estand64** [comment]
`content/guides/spring-integration/index.md` was added to create a hierarchical layout, however looking back doesn't seem to line up with the other guides so i'll remove it as it was totally my misunderstanding.

**Comment by anthonyvetter** [comment]
@estand64, let me know if you need any help with these edits. Happy to jump in.

**Comment by anthonyvetter** [comment]
@estand64, just checking in again to see if you need any help with this. Let me know.

**Comment by anthonyvetter** [comment]
Our tech writer said she could get to this on Wednesday (11/17). Hopefully that time works. If not let me know and we can try something else.

**Comment by anthonyvetter** [comment]
@estand64. Not sure if you saw, but our editor submitted you a PR with her edits. Please review and accept/reject changes. Then we can get this posted. Thanks again!

**Comment by anthonyvetter** [comment]
@estand64, any update on this? Thank you!

**Comment by estand64** [comment]
@anthonyvetter I haven't heard anything since sending back my comments.

**Pull request merged**
