### PR TITLE
Add Prometheus/Grafana guide

### PR DESCRIPTION
**Pull request by BrianMMcClain**

### CODE REVIEW

**Comment by paulczar** [comment]
I would recommend using the Bitnami Grafana Helm Chart (https://hub.helm.sh/charts/bitnami/grafana) as the community helm charts are deprecated and may be turned off by google as soon as November 13 (https://github.com/helm/charts#deprecation-timeline).

**Comment by BrianMMcClain** [comment]
> I would recommend using the Bitnami Grafana Helm Chart (https://hub.helm.sh/charts/bitnami/grafana) as the community helm charts are deprecated and may be turned off by google as soon as November 13 (https://github.com/helm/charts#deprecation-timeline).

Good call, I'll update appropriately. Thanks!

**Comment by BrianMMcClain** [comment]
Updated to use the Bitnami Grafana Helm chart. As far as I can tell, I couldn't fine one for Prometheus, but happy to update it if there is one.

**Comment by scrogatl** [comment]
Do we have a convention regarding command line prompts in the code boxes? It matters when copying because if the prompt is there the command requires editing on the local system before executing.

**Pull request merged**
