### PR TITLE
Add more app observability content

### PR DESCRIPTION
**Pull request by zmb3**
- add 3 pillars to summary
- link to guide for logging Spring Boot request/response
- add guide for exposing Prometheus metrics in Spring Boot

### CODE REVIEW

**Review by BrianMMcClain — APPROVED** [review]

**Comment by BrianMMcClain** [comment]
@zmb3 something weird happened here, I think there were two PRs open with the same changes? Wanted to give you a chance to double check everything is ok in main before closing

**Comment by zmb3** [comment]
Where’s the other PR that has these changes?

**Comment by BrianMMcClain** [comment]
Wait it was THIS PR, which I'm 99% I had just squashed and merged after reviewing like any other PR. The commit with these changes are in main, but the message in this PR isn't saying "merged these changes" as usual. You can see the actual commit to main here: https://github.com/vmware-tanzu/tanzu-dev-portal/commit/1d09382c9543cc251bf49712f3b05082dbb10d49

I'm not...totally sure what happened here?

**Comment by zmb3** [comment]
Hmm, looks like the commits were merged directly instead of via PR maybe? In any case, the code on `main` looks good so I think we're okay to close this. 🤷‍♂️

**Pull request closed without merging**
