### PR TITLE
Add tab support

### PR DESCRIPTION
**Pull request by johnharris85**
Adding support for tabbed content. Styling will probably need some tweaking (not my strong point haha) but it does work. 

Added an example by converting the git install instructions in the `/content/agile/gitflow` guide.

### CODE REVIEW

**Comment by BrianMMcClain** [comment]
Just noting down a couple observations here that someone can pick up and tweak:

- [ ] (Mobile and Desktop) Clicking on a tab takes you to the top of the page
- [ ] (Mobile) Links within tabs overflow off the page

**Comment by johnharris85** [comment]
> (Mobile and Desktop) Clicking on a tab takes you to the top of the page

I've noticed the jump to top on web sometimes too, I think it's a side-effect of how they've implemented the tab link. I'm going to see if I can hack the JS with a different implementation.

>  (Mobile) Links within tabs overflow off the page

Will make some more sacrifices to Ye Olde CSS gods and try to fix this.

**Comment by BrianMMcClain** [comment]
@johnharris85 I'm also happy to take a look at some point, or perhaps someone on our team can. Just knew if I didn't note down those observations somewhere I'd immediately forget them :)

**Comment by johnharris85** [comment]
OK https://github.com/vmware-tanzu/tanzu-dev-portal/pull/1235/commits/4e441e5151654762a50dadb831137ab0bed0e5c5 fixes the link wrapping.

**Comment by johnharris85** [comment]
Tab jumping should be fixed too now (in https://github.com/vmware-tanzu/tanzu-dev-portal/pull/1235/commits/4696efec139a665a850cc1192316cd0049d1c5cf). Basically the way tabs are implemented in Docsy is using anchor links. The existing behavior for anchor links makes this a bit messy in terms of where it should actually jump to. Also if you're clicking a tab you're looking at it anyway, so you likely don't want it to jump _anywhere_. The (somewhat hacky?) fix I've put in is just to prevent scrolling to the target if the ID starts with `#tabs-` (as it always will when using the tab shortcodes).

**Review by BrianMMcClain — APPROVED** [review]

**Pull request merged**
