### PR TITLE
Updated Tip to #1 and tip to 'Facilitator Notes & Tips'

### PR DESCRIPTION
**Pull request by lucaishovmware**
I added a tip to #1 to identify that there are risks other than technical risks. I also added a tip to note that there can be different criteria established for the 2x2 when prioritizing risks.

### CODE REVIEW

**Review by BrianMMcClain — CHANGES_REQUESTED** [review]
Hey @lucaishovmware, just a heads up, this PR is against a fairly old version of this file which has since been updated a few times, and is causing a merge conflict. I'd recommend updating your fork to match the latest just to make sure there's nothing weird happening when we merge. Thanks!

**Comment by lucaishovmware** [comment]
Much appreciated, Brian.

Learning the ins and outs of Github still … got some help and referred to the contribution guide and updated the fork as recommended!

Let me know if there’s anything else

Cheers,

Lucais

From: Brian McClain ***@***.***>
Reply to: vmware-tanzu/tanzu-dev-portal ***@***.***>
Date: Tuesday, 6 April 2021 at 10:23 PM
To: vmware-tanzu/tanzu-dev-portal ***@***.***>
Cc: Lucais Ho ***@***.***>, Mention ***@***.***>
Subject: Re: [vmware-tanzu/tanzu-dev-portal] Updated Tip to #1 and tip to 'Facilitator Notes & Tips' (#690)


@BrianMMcClain requested changes on this pull request.

Hey @lucaishovmware<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Flucaishovmware&data=04%7C01%7Clucaish%40vmware.com%7C1c72e4f58b0d4f5ed86808d8f90797d5%7Cb39138ca3cee4b4aa4d6cd83d9dd62f0%7C0%7C0%7C637533158304706990%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=oleU9wmxjzqQxOpA2Jcl%2FKuGe3hmPOOv%2ByqJ8dSbNaw%3D&reserved=0>, just a heads up, this PR is against a fairly old version of this file which has since been updated a few times, and is causing a merge conflict. I'd recommend updating your fork to match the latest just to make sure there's nothing weird happening when we merge. Thanks!

**Comment by BrianMMcClain** [comment]
No worries at all! To be honest, I'd be lying if I said I haven't done the same even recently :) It looks like you've opened a new, updated PR at #693, is that correct? If that's the case, that's totally fine, we can close this one and when you're ready to merge that one, feel free to remove the "WIP" from the title (which blocks merging until you're ready) and we can get the changes in :) Thanks!

**Comment by lucaishovmware** [comment]
Updated to remove ‘WIP’ – cheers 😊

Let me know of any next steps – would love to add more practices when possible!



From: Brian McClain ***@***.***>
Reply to: vmware-tanzu/tanzu-dev-portal ***@***.***>
Date: Wednesday, 7 April 2021 at 10:20 PM
To: vmware-tanzu/tanzu-dev-portal ***@***.***>
Cc: Lucais Ho ***@***.***>, Mention ***@***.***>
Subject: Re: [vmware-tanzu/tanzu-dev-portal] Updated Tip to #1 and tip to 'Facilitator Notes & Tips' (#690)


No worries at all! To be honest, I'd be lying if I said I haven't done the same even recently :) It looks like you've opened a new, updated PR at #693<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fvmware-tanzu%2Ftanzu-dev-portal%2Fpull%2F693&data=04%7C01%7Clucaish%40vmware.com%7C7882b7d17b7f445be3ea08d8f9d03964%7Cb39138ca3cee4b4aa4d6cd83d9dd62f0%7C0%7C0%7C637534020003232454%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=x5%2FqiExc%2BnPUzmN102Lqnr9ricz5GaFaOUXhQACx8Ts%3D&reserved=0>, is that correct? If that's the case, that's totally fine, we can close this one and when you're ready to merge that one, feel free to remove the "WIP" from the title (which blocks merging until you're ready) and we can get the changes in :) Thanks!

**Comment by BrianMMcClain** [comment]
Awesome, merged!

**Pull request closed without merging**
