### PR TITLE
GemFire Useful Statistics Blog

### PR DESCRIPTION
**Pull request by boglesby**

### CODE REVIEW

**Comment by anthonyvetter** [comment]
To help with a lot of the spelling issues, if you put technical terms in code blocks or in-line code the spell checker will ignore them. We have a [preliminary style guide](https://docs.google.com/document/d/1XsGW4hqRaPgSo7Ihh0-C8e6VjDbkVlWL7G6GgVK1SeQ/edit) that goes over some of this (and continuing to work on it). Let me know if I can help.

**Comment by anthonyvetter** [comment]
Further suggestions:
- Make the title more descriptive. Someone may find this article through search, or outside of the site's content structure. In these cases, "Most Useful Statistics" isn't going to provide any context around what this post is about. Consider "The Most Useful Statistics for Troubleshooting Tanzu Gemfire Deployments", or similar. 
- Same for the description. The description is important for SEO and people finding our posts as well as just providing readers a description of what they are about to read. Maybe turn it into 2-3 sentences with some keywords.
- We don't do a ton with Tags now, but we are working on a restructure where they will play a larger role in the sites navigation. Consider adding a `tags` section to the front matter. 

Otherwise the content looks good to me. 

I am going to open an issue against this so I can add it to our content backlog for review and tracking purposes.

**Comment by boglesby** [comment]
@anthonyvetter: Thanks a lot for the comments. I renamed it as you suggested.

**Comment by anthonyvetter** [comment]
Merged. Thanks for the contribution!

**Pull request merged**
