### PR TITLE
Hiring a Design Contractor or Vendor

### PR DESCRIPTION
**Pull request by joemoore**

### CODE REVIEW

**Comment by anthonyvetter** [comment]
Is there a reason you are using HTML tables, horizontal rules, etc, as opposed to md? Concern is that if we do format updates to layouts, it will be the md versions, and we would want that reflected uniformly throughout the site.

**Comment by joemoore** [comment]
> Is there a reason you are using HTML tables

Great question. I converted a few to MD tables and they were an absolute unreadable and unmanageable mess with all of the embedded lists and formatting. Normally I hate mixing MD and HTML but in some cases (like this) the tradeoff is worth it. If you take even one of the less complicated tables and convert it to MD I think you'll see what I mean. 

if there are any `<hr>` tags I'll remove them.

**Comment by anthonyvetter** [comment]
Understood. Tables are probably something we should tackle at some point anyway. It can be a good way of getting this kind of information across to readers in an understandable way. 

I'll send this to our editor. It's likely going to be in Gdocs again, but I will do my best to preserve the formatting. Lastly, that `Level2:` topic doesn't exist. Check out [here](https://github.com/vmware-tanzu/tanzu-dev-portal/wiki/Reference,-Hugo-Taxonomies#agile-transformation-and-practices) for existing topics.

**Comment by joemoore** [comment]
Thanks @anthonyvetter. Let me know when there is a doc; someone else would like to do some edits, too.

**Comment by joemoore** [comment]
FYI we're working on incremental changes here: https://docs.google.com/document/d/1yWQTfuuaLG1mYCSPb_m5vjypkWd4EH8K-FKgoK2yxyU/edit?pli=1#

**Comment by anthonyvetter** [comment]
[Here](https://docs.google.com/document/d/1Yu4RyzZLTZPTP-F4BVAolFnTo9jqhCR2ip1y5bYiidU/edit) is the doc I submitted. But if you are still doing edits yourself, I need to pull it back. Let me know when you are done editing and have all changes submitted. Then I will resubmit for copy editing.

**Comment by joemoore** [comment]
@anthonyvetter I don't see any new suggestions doc. Are we good to go?

**Comment by anthonyvetter** [comment]
@joemoore, I called off the copy editing since you said you were still writing. If you are done let me know and I will resubmit for final copy editing. Also, we now have 3 docs for this piece. Let me know which is the true, final version so I can be sure to submit the correct one. Thanks!

**Comment by anthonyvetter** [comment]
@joemoore, this is back from editing. Thank you for your patience. https://docs.google.com/document/d/1Yu4RyzZLTZPTP-F4BVAolFnTo9jqhCR2ip1y5bYiidU/edit
Go ahead and accept/reject changes and port them in. When you are done let me know and I can get it reviewed and merged.

**Comment by joemoore** [comment]
@anthonyvetter we're good to go!

**Comment by joemoore** [comment]
Actually hold off. I see a bunch of last minute updates

**Comment by anthonyvetter** [comment]
Standing by

**Comment by joemoore** [comment]
OK really ready this time! @anthonyvetter

**Review by anthonyvetter — APPROVED** [review]
Looks good. Merging. Thanks for your patience.

**Comment by joemoore** [comment]
Thank you!

**Pull request merged**
