### PR TITLE
New Content - Securing Kubernetes workload traffic using mTLS guide

### PR DESCRIPTION
**Pull request by ddubson**
References #1589

### CODE REVIEW

**Comment by anthonyvetter** [comment]
@ddubson, thank you for the submission!! Do you have any update on the status of this piece? It looks great so far! Are you still writing/editing? Are you ready for copy editing and review? From the checklist it looks like maybe it needs technical review? Do you need any help with that?

**Comment by anthonyvetter** [comment]
Thanks! Submitted to @lizz7000 for editing. Standby.

**Comment by anthonyvetter** [comment]
Hey @ddubson, just wanted to make sure you saw that @lizz7000 submitted you a PR to your repo with her changes yesterday. Let us know if you have any questions, or need a hand with anything.

**Comment by ddubson** [comment]
@anthonyvetter thanks for the heads up! What would be my next step, would I incorporate the changes and update this PR and notify you? Is there anything else needed?

**Comment by anthonyvetter** [comment]
@ddubson, yup exactly. As long as you are okay with all of the changes, you just need to accept the PR into your branch, and that should update this PR with the updated content as well. Then I'll send you a staging link for you to give it one final review before we merge.

**Comment by ddubson** [comment]
@anthonyvetter @lizz7000 - I made a few nitpick comments on the edits [PR](https://github.com/ddubson/tanzu-dev-portal/pull/1), but otherwise 👍🏼 .

**Comment by ddubson** [comment]
@anthonyvetter @lizz7000 - edits have been merged. Thank you!

**Review by anthonyvetter — APPROVED** [review]
Added a couple minor changes to get the tests to pass and updated front matter. Nice work!

**Comment by anthonyvetter** [comment]
Link: https://tanzu.vmware.com/developer/guides/kubernetes-mtls/

**Pull request merged**
