### PR TITLE
Reduce entries on topics pages

### LINKED ISSUE #43: Limit number of items and add links to view more on topics/patterns pages
The sections should not have more than 6 or 9 items listed or it will get unruly. We could have the Guides, Videos, Samples, Blogs headers should all link to the filtered section to view more content. Or we can add a "View more..." link at the bottom of each section.

### PR DESCRIPTION
**Pull request by jesse-martinez**
Fixes #43

### CODE REVIEW

**Comment by jesse-martinez** [comment]
Reminder to self to adjust alignment*

**Review by BrianMMcClain — CHANGES_REQUESTED** [review]
Just leaving @bryanfriedman's feedback here so it's track

looks good in general, but two questions:
1. The "VIEW ALL" button is centered on all the sections except the last one. Should they all be centered?
2. Can we get rid of the horizontal line just above the footer?

**Comment by jesse-martinez** [comment]
Sorry, totally forgot to make those changes. Just did them though and should be good to merge now! @BrianMMcClain @bryanfriedman

**Review by BrianMMcClain — APPROVED** [review]
LGTM! Added @bryanfriedman as a reviewer for a quick check as well

**Pull request merged**
