### PR TITLE
[WIP] #1609: Add content on debugging Kubernetes platforms

### PR DESCRIPTION
**Pull request by carlosonunez**
One of the most commonly needed and important skill in the world of Kubernetes
is how does one approach debugging of issues on the Platform. While much easier
said than done in practice, the first step is to know what is the exact problem
before solutioning and not to overthink it. However, how does one efficiently
and effectively do this? This article aims to enable a reader with skills to help
with debugging Kubernetes platform issues through finding the source problems
first effectively.

See [this issue](https://github.com/vmware-tanzu/tanzu-dev-portal/issues/1609)
for more context.

### CODE REVIEW

**Comment by carlosonunez** [comment]
Yup; David Wu and I paired on it (along with some other colleagues.)

**Comment by anthonyvetter** [comment]
Sounds good. Submitting for copy editing. Stand by. 
Just FYI, they are a little underwater right now, so this may take some time. I'll keep an eye on it, but feel free to ping me for updates.

**Comment by anthonyvetter** [comment]
@carlosonunez, just at first glance, this is a very long piece. I haven't read through it yet but in your opinion are there some logical break points in here where you could split this up into multiple parts? We could even explore making a Learning Path out of it if you think you could make this into 3+ logical sections. I just think it risks folks not getting through all of this content when it is 20-some pages :) And I think it is important that they do. This looks great so far!

**Comment by carlosonunez** [comment]
It is quite long :) I think we can split it up by the sections listed in the article, if you’re okay with that!

**Comment by dawu415** [comment]
@anthonyvetter Would like to understand what you mean by learning paths and if you have any examples?

**Comment by anthonyvetter** [comment]
> @anthonyvetter Would like to understand what you mean by learning paths and if you have any examples?

Learning Paths and their structure were discussed in Slack.

**Comment by dawu415** [comment]
@anthonyvetter This has been updated to be a learning path and available for review.

Thanks!

**Comment by anthonyvetter** [comment]
@dawu415, I pushed a couple changes to your fork that are now in this PR. Mostly light formatting and tag changes, as well as changes to get the link and spell check tests to pass, and fixing the conflict in custom_dict. I am passing this off to a copy editor to read through and make sure all the grammar and style is consistent. Please stand by for her changes.

**Pull request closed without merging**
