### PR TITLE
Widescreen Mode

### LINKED ISSUE #708: Create a wide screen view sitewide
Stretch logo & nav and rethink all pages sitewide to adopt a wide screen view

### PR DESCRIPTION
**Pull request by jesse-martinez**
Fixes #708

### CODE REVIEW

**Comment by craigtracey** [comment]
LGTM 

@BrianMMcClain @bryanfriedman what say you?

**Review by BrianMMcClain — APPROVED** [review]

**Comment by BrianMMcClain** [comment]
Works for me! Approved

**Comment by BrianMMcClain** [comment]
@jesse-martinez if this is good to merge, feel free to remove the WIP tag and we can merge.

**Comment by jesse-martinez** [comment]
@BrianMMcClain I made a few adjustments to the YouTube thumbnails but now its good to merge!

**Review by BrianMMcClain — CHANGES_REQUESTED** [review]
Hey @jesse-martinez, just noticed a couple image links that needed updating. I went ahead and made the changes and opened a PR to your fork. Once you merge that PR, those changes will be reflected here and we can merge. Thanks!

**Comment by jesse-martinez** [comment]
@BrianMMcClain I merged your PR. Should be good to go now?

**Review by BrianMMcClain — APPROVED** [review]

**Pull request merged**
