### PR TITLE
Fix submodule to seperate Docsy from style

### PR DESCRIPTION
**Pull request by BrianMMcClain**

### CODE REVIEW

**Comment by BrianMMcClain** [comment]
@bryanfriedman @joemoore @johnharris85 Alright, you'll notice the commit history got a little weird. That was an attempt at taking something that worked for the other half of the issue and applying it here. 

I'm not sure we can get it much cleaner than this. From a clean clone, everything should be great, but when someone pulls from main, it will leave the Font Awesome and bootstrap submodules that existed previously. It's a quick fix, with the following command:

```
rm -rf .git/modules && rm -rf themes/docsy && mkdir themes/docsy
```

But it is a manual command that people will need to run. Bryan and I discussed adding this to the `make preview` command. The downside is it will re-clone Docsy every time `make preview` is ran, but we can always leave it in for a small amount of time and then remove it later.

I've also documented another issue we're hitting, where we're actually hitting the default file handle limit on OS X, which will throw a `fatal error: pipe failed` error. This can be fixed it:

```
sudo launchctl limit maxfiles 65535 200000
ulimit -n 65535
sudo sysctl -w kern.maxfiles=100000
sudo sysctl -w kern.maxfilesperproc=65535
```

Let me know what you think, especially about the first issue, and I can make the changes and get this merged. Thanks!

**Comment by BrianMMcClain** [comment]
Ok, one last tweak: I've made two changes to the Makefile:

1. Set the ulimit when running `make preview`, this one command fixes the file handle issue without needing to run root-level commands
2. Check if the Docsy submodule needs cleaned up on build, and only run the commands that delete the `.git/module` directory, reclones Docsy, etc. if it needs to

These two changes will make the transition from the current branch and submodules to this new one much cleaner for everyone

**Comment by joemoore** [comment]
I'm seeing quite a few CSS breaks on the preview that I'm not seeing locally. 
Screen Shot 2021-08-16 at 12 06 45 PM
Screen Shot 2021-08-16 at 12 05 43 PM
Screen Shot 2021-08-16 at 12 05 22 PM

**Comment by joemoore** [comment]
Locally I'm seeing fewer CSS breakages, but still some, such as this table. 

Screen Shot 2021-08-16 at 12 08 49 PM

**Comment by BrianMMcClain** [comment]
Yup good catch on the local stuff, I noticed some of the first ones you posted in the build preview which don't manifest in the local build, I'm able to reproduce it at least. Digging into what's going on there

**Review by joemoore — COMMENTED** [review]
Technically works, has CSS issues as described.

**Comment by bryanfriedman** [comment]
@BrianMMcClain @joemoore I think my latest commit fixes the CSS issues in deploy previews. The issues that were happening both locally and on previews still need to be addressed, but this fixes the big discrepancies.

**Comment by BrianMMcClain** [comment]
@bryanfriedman @joemoore Alright I fixed the table content color, I also flipped through the rest of the site side-by-side with live and aside from a couple small alignment changes (which may be related to the side social bar since I have that on live but not in the preview, not totally sure that's the issue), everything else _seems_ to be rendering properly. Let me know if I missed something though but otherwise I think we're good?

**Comment by bryanfriedman** [comment]
LGTM. 🚢

**Review by bryanfriedman — APPROVED** [review]

**Pull request merged**
