### PR TITLE
Make netlify dev work

### PR DESCRIPTION
**Pull request by bryanfriedman**

### CODE REVIEW

**Comment by bryanfriedman** [comment]
@BrianMMcClain I've almost got this. There's a final redirect that doesn't seem to work. For some reason the path in [auth-start.js](https://github.com/vmware-tanzu/tanzu-dev-portal/blob/4d56cdae4d8ed1105bd039b66b1bcc8842c87c7c/netlify/functions/auth-start.js#L26) is `/.netlify/non-existent-path` and I don't think it's supposed to be so it ends up with an infinite redirect loop. Maybe you can figure it out, I'll look more another time as well.

**Comment by bryanfriedman** [comment]
@BrianMMcClain I found this https://github.com/netlify/cli/blob/main/src/utils/proxy.js#L144

I think this is what's causing the problem. The `nf_jwt` cookie...

1. needs to be set without the `domain` parameter for localhost (easy fix similar to what I did with the other cookie)
2. needs to be set earlier I think. It's currently getting set in `auth-callback` instead of `auth-start` based on looking at this code. I think since `token` in the netlify cli code is not being set it never sets the URL. May have to adjust the flow a little bit for localhost...

**Comment by bryanfriedman** [comment]
Also a note, we should move this line https://github.com/vmware-tanzu/tanzu-dev-portal/blob/main/netlify/functions/auth-callback.js#L124 to a separate file ideally and read it in to a variable. This is pretty rough to maintain as is...

**Comment by BrianMMcClain** [comment]
@bryanfriedman This sets the `jwt` token now, but still getting the redirect loop. Looking into if it needs to be set earlier like you mentioned

**Comment by bryanfriedman** [comment]
@BrianMMcClain Can you give this a really quick once over? I think it's good to merge. I tested in the deploy preview and workshops launch okay, nothing else should really be affected in prod, only locally, where it also seems to work. If it looks good, feel free to approve and merge.

**Review by BrianMMcClain — APPROVED** [review]

**Pull request merged**
