### PR TITLE
Add Amplitude tracking for theme toggle

### PR DESCRIPTION
**Pull request by bryanfriedman**

### CODE REVIEW

**Comment by bryanfriedman** [comment]
@BrianMMcClain I think this gives us at least some info on who's using the themes. Take a look and if it looks okay, feel free to merge.

**Comment by BrianMMcClain** [comment]
@bryanfriedman this looks good to me, seems like events are getting sent to amplitude. My only thought is that this is just capturing then the theme is changed, and if our goal is to see the distribution of theme usage on the site, this might not get the full picture, or if it does it's a bit indirect. My other thought is that we could include what theme is active in the user properties that are sent along with each metric maybe? Either way, I'm happy to merge as is, just want to make sure we're getting the info you wanted out of it :)

**Review by BrianMMcClain — APPROVED** [review]

**Comment by bryanfriedman** [comment]
@BrianMMcClain I did add the code to store the latest selected theme as a user property. https://github.com/vmware-tanzu/tanzu-dev-portal/pull/919/files#diff-517d9f00e1d633cbc4e8cae8a0b796874f78d8f7c7017315ba8dd6132970eca6R77

I guess I'm not certain that it's working properly, but that was the intent.

**Comment by bryanfriedman** [comment]
Actually it's definitely not working properly, haha. Let me push a fix.

**Review by BrianMMcClain — APPROVED** [review]

**Pull request merged**
